alias ll="ls -Glahs"
alias psgrep="ps aux | grep -v grep | grep"
alias ri="ri -f ansi"
alias pcat="pygmentize -f terminal256 -O style=tango -g"
alias hex="openssl rand -hex"
alias dotfiles="wget -q -O - https://raw.github.com/fnando/dotfiles/master/`basename $(echo $SHELL)` | bash"
