alias ll="ls -Glahs"
alias psgrep="ps aux | grep -v grep | grep"
alias ri="ri -f ansi"
alias reload="source ~/.bash_profile"
alias pcat="pygmentize -f terminal256 -O style=tango -g"
alias hex="openssl rand -hex"
