#!/usr/bin/env bash

PATH="$PATH:$HOME/local/bin:/usr/local/bin"

terminal-notifier \
  -message "CCC has finished a backup routine" \
  -ignoreDnD \
  -title "Carbon Copy Clone" \
  -group CCC \
  &> /dev/null
