#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
  interface=${1:-en0}
  ifconfig $interface | grep 'inet ' | cut -d' ' -f2
else
  interface=${1:-eth0}
  ifconfig $interface | grep 'inet addr' | sed -E 's/[^:]+:([^ ]+).*$/\1/'
fi
