source $HOME/.zsh/user.sh
source $HOME/.zsh/general.sh
source $HOME/.zsh/keybindings.sh
source $HOME/.zsh/options.sh
source $HOME/.zsh/prompt.sh
source $HOME/.zsh/cd.sh
source $HOME/.zsh/md.sh
source $HOME/.zsh/rscp.sh
source $HOME/.zsh/bundler.sh
source $HOME/.zsh/git.sh
