AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0

  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - config/environments/**/*.rb
    - bin/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/**.rb
    - config/config.rb

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/IndentArray:
  EnforcedStyle: consistent

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Naming/UncommunicativeMethodParamName:
  Enabled: false

Lint/Debugger:
  Exclude:
    - test/**/*

Style/TrailingUnderscoreVariable:
  Enabled: false
