export SHELL_NAME="bash"

source $HOME/.bash/user.sh
source $HOME/.bash/exports.sh
source $HOME/.bash/aliases.sh
source $HOME/.bash/specific.sh
source $HOME/.bash/other.sh
source $HOME/.bash/gem_completion.sh
source $HOME/.bash/cd.sh
source $HOME/.bash/md.sh
source $HOME/.bash/rscp.sh
source $HOME/.bash/bundler.sh
source $HOME/.bash/foreman.sh
source $HOME/.bash/git.sh
source $HOME/.bash/psgrep.sh
source $HOME/.bash/tmux.sh
source $HOME/.bash/rvm.sh
source $HOME/.bash/rbenv.sh
source $HOME/.bash/prompt.sh
