alias cdto="cd `osascript $HOME/.bash/scripts/finder-path.applescript` &> /dev/null"
alias redis="redis-server"
alias growl="growlnotify"
alias js="java -jar $HOME/Library/Java/Extensions/js.jar -opt -1"
alias ls="ls -G"
alias ll="ls -Glahs"
alias psgrep="ps aux | egrep -v egrep | egrep"
alias showip="curl http://f.simplesideias.com.br/ip.php; echo; ifconfig | grep broadcast | sed 's/.*inet \(.*\) netmask.*/\1/'"
alias lock="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
alias top="top -o cpu"
alias mysql="mysql --auto-rehash=TRUE"
alias ni="lsof -i -Pn"
alias make="make -j2"
alias cleanup="sudo rm -rf /private/var/log/asl/*"
alias xmlget="curl -X GET -H 'Accept: application/xml'"
alias jsonget="curl -X GET -H 'Accept: application/json'"
alias xmlpost="curl -X POST -H 'Accept: application/xml'"
alias xmlput="curl -X PUT -H 'Accept: application/xml'"
alias xmldelete="curl -X DELETE -H 'Accept: application/xml'"
alias r="rails"
alias rg="rvm gemset use"
alias autotest="RUBYLIB='.' autotest"
alias macirb="macirb --simple-prompt -f"
alias newgem="thor gem"
