alias cleanup="sudo rm -rf /private/var/log/asl/*"
alias js="java -jar $HOME/Library/Java/Extensions/js.jar -opt -1"
alias ll="ls -Glahs"
alias lock="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
alias ls="/bin/ls -G"
alias macirb="macirb --simple-prompt -f"
alias make="make -j2"
alias mysql="mysql --auto-vertical-output"
alias ni="lsof -i -Pn"
alias psgrep="ps aux | egrep -v egrep | egrep"
alias showip="curl http://f.simplesideias.com.br/ip.php; echo; ifconfig | grep broadcast | sed 's/.*inet \(.*\) netmask.*/\1/'"
alias top="top -o cpu"
alias vim="vim -N"
alias brew="RUBYLIB=/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/ brew"
